spring:
  jpa:
    open-in-view: false
  application:
    name: loan
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_library}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:simple_password}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

api:
  base-url: ${API_BASE_URL:http://localhost:8080}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    amqp-port: ${RABBITMQ_AMQP_PORT:5672}
    ui-port: ${RABBITMQ_MANAGEMENT:15672}
    user: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
